-- Clone as ACCOUNTADMIN, then hand access to working roles

USE ROLE ACCOUNTADMIN;

-- Clone the sample DB into your workspace
CREATE DATABASE IF NOT EXISTS TASTY_BYTES_CLONE CLONE TASTY_BYTES;

-- Give SYSADMIN full control so it can manage the clone
GRANT OWNERSHIP ON DATABASE TASTY_BYTES_CLONE TO ROLE SYSADMIN REVOKE CURRENT GRANTS;

-- Create analytics schema
USE ROLE SYSADMIN;
USE DATABASE TASTY_BYTES_CLONE;
CREATE SCHEMA IF NOT EXISTS ANALYTICS;

-- Grant access to working roles
USE ROLE SECURITYADMIN;

-- Database usage (grant each role separately)
GRANT USAGE ON DATABASE TASTY_BYTES_CLONE TO ROLE ANALYTICS_DEV_ROLE;
GRANT USAGE ON DATABASE TASTY_BYTES_CLONE TO ROLE POWERBI_READ_ROLE;

-- Schema usage
GRANT USAGE ON SCHEMA TASTY_BYTES_CLONE.RAW_POS TO ROLE ANALYTICS_DEV_ROLE;
GRANT USAGE ON SCHEMA TASTY_BYTES_CLONE.ANALYTICS TO ROLE ANALYTICS_DEV_ROLE;
GRANT USAGE ON SCHEMA TASTY_BYTES_CLONE.ANALYTICS TO ROLE POWERBI_READ_ROLE;

-- Dev role: create & read
GRANT CREATE VIEW ON SCHEMA TASTY_BYTES_CLONE.ANALYTICS TO ROLE ANALYTICS_DEV_ROLE;
GRANT SELECT ON ALL TABLES  IN SCHEMA TASTY_BYTES_CLONE.RAW_POS TO ROLE ANALYTICS_DEV_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA TASTY_BYTES_CLONE.RAW_POS TO ROLE ANALYTICS_DEV_ROLE;

-- BI role: read only
GRANT SELECT ON ALL VIEWS   IN SCHEMA TASTY_BYTES_CLONE.ANALYTICS TO ROLE POWERBI_READ_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA TASTY_BYTES_CLONE.ANALYTICS TO ROLE POWERBI_READ_ROLE;

-- ✅ Optional sanity check
USE ROLE ANALYTICS_DEV_ROLE;
USE WAREHOUSE ANALYTICS_WH;
USE DATABASE TASTY_BYTES_CLONE;
USE SCHEMA ANALYTICS;

SELECT COUNT(*) AS MENU_ROWS
FROM TASTY_BYTES_CLONE.RAW_POS.MENU;
